/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ApiPublicFacebookCallbackRouteImport } from './routes/api/public/facebook-callback'
import { Route as ApiPublicFacebookLoginRouteImport } from './routes/api/public/facebook-login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFacebookCallbackRoute =
  ApiPublicFacebookCallbackRouteImport.update({
    id: '/api/public/facebook-callback',
    path: '/api/public/facebook-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFacebookLoginRoute = ApiPublicFacebookLoginRouteImport.update({
  id: '/api/public/facebook-login',
  path: '/api/public/facebook-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/api/public/facebook-callback': typeof ApiPublicFacebookCallbackRoute
  '/api/public/facebook-login': typeof ApiPublicFacebookLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/api/public/facebook-callback': typeof ApiPublicFacebookCallbackRoute
  '/api/public/facebook-login': typeof ApiPublicFacebookLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/api/public/facebook-callback': typeof ApiPublicFacebookCallbackRoute
  '/api/public/facebook-login': typeof ApiPublicFacebookLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/api/public/facebook-callback'
    | '/api/public/facebook-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/api/public/facebook-callback'
    | '/api/public/facebook-login'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/api/public/facebook-callback'
    | '/api/public/facebook-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ApiPublicFacebookCallbackRoute: typeof ApiPublicFacebookCallbackRoute
  ApiPublicFacebookLoginRoute: typeof ApiPublicFacebookLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/facebook-callback': {
      id: '/api/public/facebook-callback'
      path: '/api/public/facebook-callback'
      fullPath: '/api/public/facebook-callback'
      preLoaderRoute: typeof ApiPublicFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/facebook-login': {
      id: '/api/public/facebook-login'
      path: '/api/public/facebook-login'
      fullPath: '/api/public/facebook-login'
      preLoaderRoute: typeof ApiPublicFacebookLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ApiPublicFacebookCallbackRoute: ApiPublicFacebookCallbackRoute,
  ApiPublicFacebookLoginRoute: ApiPublicFacebookLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
